import {ExtendEventName} from "./interfaces";
export const EVENT_TEMPFRAME_APPENDED="EVENT_TEMPFRAME_APPENDED"
export const EVENT_TEMPFRAME_REMOVED="EVENT_TEMPFRAME_REMOVED"

export const EVENT_NEED_MASK="EVENT_NEED_MASK"
export const EVENT_NO_MASK="EVENT_NO_MASK"

export const EVENT_FRAME_DRAWING_TRIGGERED="EVENT_FRAME_DRAWING_TRIGGERED"
export const EVENT_FRAME_DRAWING_SATRTED="EVENT_FRAME_DRAWING_SATRTED"
export const EVENT_FRAME_DRAWING_MOVING="EVENT_FRAME_DRAWING_MOVING"
export const EVENT_FRAME_DRAWING_STOPPED="EVENT_FRAME_DRAWING_STOPPED"
export const EVENT_FRAME_DRAWING_SUCCESS="EVENT_FRAME_DRAWING_SUCCESS"
export const EVENT_FRAME_DRAWING_FAIELD="EVENT_FRAME_DRAWING_FAIELD"

export const EVENT_INFOMATION="EVENT_INFOMATION"
export const EVENT_FRAME_HIDE="EVENT_FRAME_HIDE"
export const EVENT_FRAME_SHOW="EVENT_FRAME_SHOW"

export const EVENT_FRAME_MOVE_BEGIN="EVENT_FRAME_MOVE_BEGIN"
export const EVENT_FRAME_MOVING="EVENT_FRAME_MOVING"
export const EVENT_FRAME_MOVE_END="EVENT_FRAME_MOVE_END"


export const EVENT_FRAME_MOUSE_HOVER = "EVENT_FRAME_MOUSE_HOVER"
export const EVENT_FRAME_RESIZE_TRIGGERED = "EVENT_FRAME_RESIZE_TRIGGERED"
export const EVENT_FRAME_RESIZE_BEGIN="EVENT_FRAME_RESIZE_BEGIN"
export const EVENT_FRAME_RESIZING="EVENT_FRAME_RESIZING"
export const EVENT_FRAME_RESIZE_END="EVENT_FRAME_RESIZE_END"

export const EVENT_FRAME_AT_BUTTON = "EVENT_FRAME_AT_BUTTON"
export const EVENT_FRAME_OUT_BUTTON = "EVENT_FRAME_OUT_BUTTON"

export const EVENT_MOUSE_LBTN_PRESSED = "EVENT_MOUSE_LBTN_PRESSED"
export const EVENT_MOUSE_LBTN_RELEASED = "EVENT_MOUSE_LBTN_RELEASED"

export const EVENT_FRAME_TOGGLE_FOLDBODY = "EVENT_FRAME_TOGGLE_FOLDBODY"
export const EVENT_FRAME_TOGGLE_MINIMIZE = "EVENT_FRAME_TOGGLE_MINIMIZE"
export const EVENT_FRAME_TOGGLE_TOOLS = "EVENT_FRAME_TOGGLE_TOOLS"
export const EVENT_FRAME_TOGGLE_PINE ="EVENT_FRAME_PINE"
export const EVENT_FRAME_SAVE_AS = "EVENT_FRAME_SAVE_AS"
export const EVENT_FRAME_SET_TITLE = "EVENT_FRAME_SET_TITLE"


// export  const EVENTS = {
//     SELECTION_START: 'SELECTION_START',
//     SELECTION_SUCCESS:"SELECTION_SUCCESS",
//     TEMPFRAME_APPENDED:"TEMPFRAME_APPENDED",
//     TEMPFRAME_REMOVED:"TEMPFRAME_REMOVED",
//     NEED_MASK:"NEED_MASK",
//     NO_MASK:"NO_MASK",
//     FRAME_DRAWING_TRIGGERED:"frameDrawingTriggered",
//     FRAME_DRAWING_SATRTED:"frameDrawingSatrted",
//     FRAME_DRAWING_MOVING:"frameDrawingMoving",
//     FRAME_DRAWING_STOPPED:"frameDrawingStopped",
//     FRAME_DRAWING_SUCCESS:"FRAME_DRAWING_SUCCESS",
//     FRAME_DRAWING_FAIELD:"FRAME_DRAWING_FAIELD",
//     INFOMATION:"COMMON_SHOW_INFO",
// }